"""
RAG query endpoint.

The route handler is intentionally thin: validation is handled by Pydantic,
security by middleware + use case, and errors by the exception handlers in main.py.
"""
from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status

from aegis.application.dtos.rag_dtos import (
    QueryRequest,
    QueryResponse,
    SecurityRejectionResponse,
)
from aegis.application.use_cases.query_rag import QueryRAGUseCase, SecurityViolationError
from aegis.interface.api.dependencies import get_query_use_case

router = APIRouter(prefix="/api/v1", tags=["rag"])


@router.post(
    "/query",
    response_model=QueryResponse,
    responses={
        400: {
            "model": SecurityRejectionResponse,
            "description": "Query blocked by security policy.",
        },
        403: {"description": "Forbidden: missing or invalid API key."},
        429: {"description": "Rate limit exceeded."},
    },
    summary="Submit a query to the RAG pipeline",
    description=(
        "Submits a natural-language question through the SecurityGateway, "
        "retrieves relevant context from the vector store, and returns a "
        "grounded answer generated by the configured LLM."
    ),
)
async def query_rag(
    request: QueryRequest,
    use_case: Annotated[QueryRAGUseCase, Depends(get_query_use_case)],
) -> QueryResponse:
    try:
        return await use_case.execute(request)
    except SecurityViolationError as exc:
        # Return a structured 400 instead of 500 to communicate the rejection cause.
        # The detail is intentionally vague to avoid revealing detection logic.
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "message": str(exc),
                "query_hash": exc.query_hash[:16],  # truncated for logs; full hash in audit
                "threat_level": exc.threat_level,
            },
        ) from exc
